src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

src/homeworker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', include('account.urls')),
    path(_('kakeibo/'), include('kakeibo.urls')),
    path(_('blog/'), include('blog.urls', namespace='blog')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/kakeibo/urls.py
from django.urls import path

from .views import kakeibo_page, kakeibo_list

app_name = 'kakeibo'

urlpatterns = [
    path('', kakeibo_page, name='input'),
    path('list/', kakeibo_list, name='show'),
]

src/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="description" content="{% block metadescription %}{% endblock %}">
      <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500|Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" >
      <link rel="stylesheet" type="text/css" href="{% static 'css/top-navbar.css' %}" >
      <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}" >
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
      {% block custom_static %}{% endblock custom_static %}
      <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="container-fluid my_navbar">
        {% include 'top-navbar.html' %}
    </div>
    {% block content %}
    {% endblock %}

    <div>
        {% include 'footer.html' %}
    </div>
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block custom_js %}{% endblock custom_js %}
</body>
</html>

src/templates/footer.html
<footer class="footer navbar-fixed-bottom my_footer ">
    <div class="container">
        <p class="text-center">&copy; HomeWorker, With, Django</p>
    </div>
</footer>

src/templates/header.html
{% load staticfiles %}
<header>
    <div style="text-align:center">
        <a href="{% url 'dashboard' %}">HOME WORKER</a>
    </div>
</header>

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">All Products</a>
            {% for cat in links %}
                <a class="dropdown-item" href="#"></a>
            {% endfor %}
        </div>
      </li>
        {% if item_count > 0 %}
          <li class="nav-item">
           <a class="nav-link" href="#"><i class="fas fa-shopping-cart">#</i></a>
          </li>
        {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0" action="#" method="get">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

src/templates/navbar2.html
{% load static %}

{% block custom_static%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}" >
    <style>
        .banner {
            width: 100%;
            height: 100vh;
            background: linear-gradient(rgba(0, 0, 0, .7), rgba(0, 0, 0, .8)), url({% static 'media/banner-bg.jpeg' %}) center no-repeat;
            background-size: cover;
        }
        .top-nav {
            height: 15vh;
            width: 100%;
            background: linear-gradient(rgba(0, 0, 0, .8), rgba(0, 0, 0, .8)), url({% static 'media/nav-bg.jpeg' %}) no-repeat 50% 0;
            background-size: cover;
            position: fixed;
            top: -15vh;
            z-index: 50;
            transition: top .4s;
        }
        .bottom-nav {
            width: 100%;
            height: 85vh;
            background: linear-gradient(rgba(0, 0, 0, .8), rgba(0, 0, 0, .8)), url({% static 'media/nav-bg.jpeg' %}) no-repeat 50% -15vh;
            background-size: cover;
            position: fixed;
            bottom: -85vh;
            transition: bottom .4s;
        }


    </style>
{% endblock custom_static %}

<div class="navbar-container">
    <div class="banner">
            <div class="logo">
                <a href="#"><img src="{% static 'media/logo.png' %}"></a>
            </div>
            <div class="btn-wrapper">
                <button class="banner-btn">Explore More</button>
            </div>
        </div>

        <div class="nav-wrapper">
            <div class="hamburger-menu">
                <div class="line line-1"></div>
                <div class="line line-2"></div>
                <div class="line line-3"></div>
            </div>

            <nav class="top-nav">
                <ul class="nav-list">
                    <li>
                        <a href="#" class="nav-link" data-text="Home">Home</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link" data-text="About Us">About Us</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link" data-text="Our Team">Our Team</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link" data-text="Services">Services</a>
                    </li>
                    <li>
                        <a href="#" class="nav-link" data-text="Contact">Contact</a>
                    </li>
                </ul>
            </nav>

            <nav class="bottom-nav">
                <ul class="icons">
                    <li class="icon-item">
                        <a href="#" class="icon-link"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li class="icon-item">
                        <a href="#" class="icon-link"><i class="fab fa-youtube"></i></a>
                    </li>
                    <li class="icon-item">
                        <a href="#" class="icon-link"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="icon-item">
                        <a href="#" class="icon-link"><i class="fab fa-google-plus-g"></i></a>
                    </li>
                </ul>
            </nav>
        </div>
</div>

{% block custom_js %}
    <script src="{% static 'js/navbar.js' %}"></script>
{% endblock custom_js %}

src/templates/top-navbar.html
{% load i18n %}
<div class="container">
    <div class="nav-content">
        <div class="top-log">
            <a href="{% url 'dashboard' %}">HOMEWORKER</a>
        </div>

        <div class="my_custom_menu">
            <ul>
              {% if request.user.is_authenticated and request.user.first_name %}
                  <li>
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          MENU
                      </a>
                      <div class="dropdown-menu dropdown-menu-right">
                          <a href="{% url 'kakeibo:input' %}" class="dropdown-item">kakeibo</a>
                          <a href="#" class="dropdown-item">#</a>
                          <a href="#" class="dropdown-item">#</a>
                      </div>
                  </li>
                  <li>
                      Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          {{ request.user.first_name }}<i class="fas fa-user-circle"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right">
                          <a href="#" class="dropdown-item">about</a>
                          <a href="#" class="dropdown-item">settings</a>
                          <a href="{% url 'logout' %}" class="dropdown-item">signout</a>
                      </div>
                  </li>
                  <li>
                      <a href="{% url 'logout' %}">Sign Out<i class="fas fa-sign-out-alt"></i></a>
                  </li>
              {% else %}
                  <li>
                      <a href="{% url 'register' %}">Sign Up<i class="fas fa-user-plus"></i></a>
                  </li>
                  <li>
                      <a href="{% url 'login' %}">Sign In<i class="fas fa-sign-in-alt"></i></a>
                  </li>
              {% endif %}
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          {% trans "Language" %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected dropdown-item"{% else %} class="dropdown-item"{% endif %}>
                                {{ language.name_local }}
                            </a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>